// Enum MagicLeapPrivileges.EMagicLeapPrivilege
enum class FEMagicLeapPrivilege : uint8 {
	Invalid
	BatteryInfo
	CameraCapture
	ComputerVision
	WorldReconstruction
	InAppPurchase
	AudioCaptureMic
	DrmCertificates
	Occlusion
	LowLatencyLightwear
	Internet
	IdentityRead
	BackgroundDownload
	BackgroundUpload
	MediaDrm
	Media
	MediaMetadata
	PowerInfo
	LocalAreaNetwork
	VoiceInput
	Documents
	ConnectBackgroundMusicService
	RegisterBackgroundMusicService
	PcfRead
	PwFoundObjRead
	NormalNotificationsUsage
	MusicService
	ControllerPose
	GesturesSubscribe
	GesturesConfig
	AddressBookRead
	AddressBookWrite
	AddressBookBasicAccess
	CoarseLocation
	FineLocation
	HandMesh
	WifiStatusRead
	SocialConnectionsInvitesAccess
	SecureBrowserWindow
	EMagicLeapPrivilege_MAX
};

